server:
  port: 8080

redis:
  addr: 127.0.0.1               #Redis服务器IP
  port: 6379                    #Redis的端口号
  auth:                         #访问密码
  max_active: 1024             #可用连接实例的最大数目，默认值为8。如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
  max_idle: 200                #控制一个pool最多有多少个状态为idle(空闲的)的jedis实例，默认值也是8
  max_wait: 10000              #等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
  time_out: 10000              #连接等待时间
  test_on_borrow: true        #在borrow一个jedis实例时，是否提前进行validate操作；如果为true，则得到的jedis实例均是可用的